printWidth: 88
semi: false
singleQuote: true
tabWidth: 2
trailingComma: 'es5'
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
      - '*.mjs'
    options:
      parser: 'typescript'
  - files: '*.json'
    options:
      parser: 'json'
  - files: '*.html'
    options:
      parser: 'html'
