version: '3.9'
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      TZ: ${APP_TIME_ZONE}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_INITDB_ARGS: '--auth=md5'
    volumes:
      - db_data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: '512m'
        max-file: '30'
    ports:
      - '5432:5432'
    networks:
      - one-net

volumes:
  db_data:

networks:
  one-net:
    external: false
